# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pl_verion": "00_utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://ayasyrev.github.io/pl_util/"

git_url = "https://github.com/ayasyrev/pl_util/tree/master/"

def custom_doc_links(name): return None
